### ISSUE TITLE
Port publishing does not work when trying to serve book from inside container

### ISSUE THREAD

**Issue by wonderfulspam** [Michael-F-Bryan/mdbook-docker-image#1]
Not sure if this belongs here; the change may have to be made in https://github.com/rust-lang/mdBook.

When trying to use the Docker image as a web server for local development, the application listens on `localhost` / `127.0.0.1` rather than `0.0.0.0` which means that port publishing fails.

Sample `docker-compose` setup:
```yml
version: "3.4"
services:
  mdbook:
    image: michaelfbryan/mdbook-docker-image:latest
    container_name: mdbook
    entrypoint: []
    # Build book in /tmp/build and serve it
    command: sh -c "/bin/mdbook serve -d /tmp/build /book"
    volumes:
      - ./:/book
    ports:
      - 3000:3000
```

The workaround for now is to add `network_mode: host`.
